#%RAML 1.0 Trait

usage: Headers for application
headers:
  
  client_id:
   description: Client Id
   type: string
   example: abcd

  client_secret:
    description: Client Secret
    type: string
    example: abcd 